#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "pytition"
name = "Pytition"
description.en = "Host privacy-friendly online petitions"
description.fr = "Hébergez des pétitions en ligne respectueuses de la vie privée"

version = "2.7~ynh2"

maintainers = ["Salamandar"]

[upstream]
license = "BSD-3-Clause"
website = "https://pytition.org"
demo = "https://demo.pytition.org"
admindoc = "https://pytition.readthedocs.io/en/latest/"
code = "https://github.com/pytition/Pytition"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pytition"

    [install.init_main_permission]
    help.en = "If private, only Yunohost users will be able to sign petitions."
    help.fr = "Si privé, seuls des utilisateurs Yunohost pourront signer des pétitions."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Administrator password"
    help.fr = "Mot de passe administrateur"
    type = "password"

[resources]
    [resources.sources.main]
    url = "https://github.com/pytition/Pytition/archive/refs/tags/v2.7.tar.gz"
    sha256 = "3ed7ea64765a259a453cbd58569ed0177e40a4f248995bd0c613966d1d40d60e"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server python3 virtualenv gettext libzip-dev libssl-dev default-libmysqlclient-dev uwsgi uwsgi-plugin-python3 python3-uwsgidecorators"

    [resources.database]
    type = "mysql"
